### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by 30155** [30155/protospace-36764#1]
#URL
https://protospace-36764.herokuapp.com/

**Comment by snkw-works** [comment]
@30155 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
